apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abies-platform
  namespace: argocd
spec:
  project: abies
  source:
    repoURL: git://abies-git.gitops.svc.cluster.local/abies.git
    targetRevision: main
    path: abies-platform/charts/abies
    helm:
      releaseName: abies
      skipTests: true
      valueFiles:
        - ../../environments/server/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: abies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
