apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: abies
  namespace: argocd
spec:
  description: Abies application on this server
  sourceRepos:
    - git://abies-git.gitops.svc.cluster.local/abies.git
  destinations:
    - namespace: abies
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
