apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: abies
resources:
  - namespace.yaml
  - config.yaml
  - storage.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - network-policy.yaml
images:
  - name: abies-api
    newName: ghcr.io/shubham235808/abies-api
    newTag: "REPLACE_WITH_GIT_SHA"
  - name: abies-web
    newName: ghcr.io/shubham235808/abies-web
    newTag: "REPLACE_WITH_GIT_SHA"
