apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "abies.fullname" . }}-config
  labels:
    {{- include "abies.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  APP_ORIGIN: {{ .Values.app.origin | quote }}
  COOKIE_SECURE: {{ .Values.app.secureCookie | quote }}
  NODE_ENV: production
