{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "abies.fullname" . }}
  labels:
    {{- include "abies.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      {{- if not (regexMatch "^[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+$" .Values.ingress.host) }}
      hosts: [{{ .Values.ingress.host | quote }}]
      {{- end }}
  rules:
    - {{- if not (regexMatch "^[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+$" .Values.ingress.host) }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "abies.fullname" . }}-frontend
                port: {number: 3000}
{{- end }}
