{{- if and .Values.ingress.enabled .Values.ingress.defaultCertificate }}
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  labels:
    {{- include "abies.labels" . | nindent 4 }}
spec:
  defaultCertificate:
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
